
const dataCharacters = [
		{id: "000",
		altText: "The Mandalorian wears his signature hetmut and regalia",
		character: "The Mandalorian",
		bio: "The Mandalorian, is a sobriquet for <a href=\"https://starwars.fandom.com/wiki/Din_Djarin\">Din Djarin</a>. He was orphaned as a child and adopted into the Mandalorian culture and became a bounty hunter. He is portrayed by <a href=\"https://en.wikipedia.org/wiki/Pedro_Pascal\">Pedro Pascal</a>.",
		img: "https://storage.googleapis.com/caraimgs/mando.jpg",
		url: "https://en.wikipedia.org/wiki/The_Mandalorian_(Star_Wars_character)",
		},
		{id: "111",
		altText: "The Child drinks a cup of soup from a mug.",
		character: "The Child",
		bio: "The Child is an infant member of the same unnamed alien species as the popular Star Wars character Yoda, with whom he shares a strong ability in the Force. Though 50 years old, he resembles an infant. ",	
		img: "https://storage.googleapis.com/caraimgs/babyyoda.jpeg",
		url: "https://en.wikipedia.org/wiki/The_Child_(Star_Wars)",
		},
		{id: "222",
		altText: "Greef Karga stands against a blue sky and stares wistfully into the distance.",
		character: "Greef Karga",
		bio: "Greef Karga is a leader of the Bounty Hunter\'s Guild, and provides the show\'s title character with the bounty that leads him to meet the Child. He is portrayed by <a href=\"https://en.wikipedia.org/wiki/Carl_Weathers\">Carl Weathers</a>\.",
		img: "https://storage.googleapis.com/caraimgs/greef.jpg",
		url: "https://en.wikipedia.org/wiki/Greef_Karga",
		},
		{id: "333",
		altText: "IG-11 Stands with weapon ready.",
		character: "IG-11",
		bio: "IG-11 is an extremely deadly and efficient bounty hunter droid whose instructions are to initially attempt to capture and kill an alien known as the Child. He is later reprogrammed to protect the child at all costs.",
		img: "https://storage.googleapis.com/caraimgs/nurse.jpg",
		url: "https://en.wikipedia.org/wiki/IG-11",
		},
	]

export default dataCharacters;